collections:
  - name: "about"
    label: "About"
    files:
      - file: "pages/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation"
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "research"
    label: "Research"
    files:
      - file: "pages/research/index.md"
        label: "Research Page"
        name: "research"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation"
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }
          - { label: "Body", name: "body", widget: "markdown" }

  # Repeat similarly for "people", "publications", "software"
